remove qlmarkdown files, add readme for install

diff --git a/functions/addpath b/functions/addpath
--- a/functions/addpath
+++ b/functions/addpath
@@ -1,7 +1,7 @@
 # addpath
 
 # Adds values to the top of the PATH enviroment variable.
-# If a value is already there it is put at the top.
+# If a value is already in PATH it is removed and placed at the top.
 
 # If the provided folder does not exist it is not added to the PATH
 # variable.
@@ -17,7 +17,7 @@ addpath() {
 
 	PATH=$(echo $PATH | sed $extendedOption 's/(^|:)$1(:|$)/:/g')
 
-	# Remove leading and trailing ':' that may happen
+	# Remove leading and trailing  `:` that may happen
 	PATH=${PATH#:}
 	PATH=${PATH%:}
 
@@ -25,7 +25,7 @@ addpath() {
 	if [[ -d $1 ]]; then
 		export PATH=$1:$PATH
 	else
-		echo "addpath called with invalid directory: '$1'" >&2
+		echo "addpath cannot add invalid directory: '$1'" >&2
 	fi
 }
 
