first pass in simplifying gache

diff --git a/scripts/gache b/scripts/gache
--- a/scripts/gache
+++ b/scripts/gache
@@ -77,19 +77,39 @@ if [[ $# -eq 0 ]]; then
 fi
 
 
-# TODO after this, the allowed commands follow one of two formats:
-# gache <command> [<n>]
-# gache <command> [<message>]
-# it may be simpler to have code that parses first the comand and
-# index/message to use, and then just execute it
-# instead of having to check repeatedly for the format of the command line
+# Preparing arguments for rest of commands
+subcommand=$1
+shift
+message="$@"
+
+stashIndex=$2
+autozeroed='false'
+if [[ -z $stashIndex ]]; then
+	stashIndex=0
+	autozeroed='true'
+fi
+
+intRegex='^[0-9]+$'
+if [[ ! $stashIndex =~ $intRegex ]]; then
+	[[ -t 1 ]] && echo 'Invalid arguments: `gache <subcommand> <n>` second argument must be a positive integer' >&2
+	exit $error_invalidArguments
+fi
+
+stashList=()
+IFS=$'\n'
+for item in $(git stash list); do
+	stashList+=("$item")
+done
+unset IFS
+
+if [[ $stashIndex -ge ${#stashList[@]} ]]; then
+	[[ -t 1 ]] && echo 'Stash index out of bounds' >&2
+	exit $error_outOfBounds
+fi
 
 
 # gache save|s [<message>]
-if [[ $1 == 'save' || $1 == 's' ]]; then
-	shift
-
-	message="$@"
+if [[ $subcommand == 'save' || $subcommand == 's' ]]; then
 	if [[ -n $message ]]; then
 		git stash save --include-untracked -- "$message"
 	else
@@ -100,57 +120,22 @@ if [[ $1 == 'save' || $1 == 's' ]]; then
 		exit $error_stashError
 	fi
 	exit 0
-
 fi
 
+
 # TODO # gache index|i
+# TODO # gache <n>
 
 
-# Any other commands afterwards work over the existing stashes
-
-# Getting the list of available stashes
-stashList=()
-IFS=$'\n'
-for item in $(git stash list); do
-	stashList+=("$item")
-done
-unset IFS
-
-intRegex='^[0-9]+$'
-
-
-# gache <n>
-# if [[ $1 =~ $intRegex ]]; then
-# 	if [[ $# -gt 1 ]]; then
-# 		[[ -t 1 ]] && echo 'Invalid arguments: `gache <n>` does not accept any more arguments' >&2
-# 		exit $error_invalidArguments
-# 	fi
-
-# 	if [[ $1 -ge ${#stashList[@]} ]]; then
-# 		[[ -t 1 ]] && echo 'Stash index out of bounds' >&2
-# 		exit $error_outOfBounds
-# 	fi
-# fi
+# Commands after this do not accept extra arguments
+if [[ $# -gt 1 ]]; then
+	[[ -t 1 ]] && echo 'Invalid arguments: `gache <subcommand> <n>` does not accept any more arguments' >&2
+	exit $error_invalidArguments
+fi
 
 
 # gache pop|p [<n>]
-if [[ $1 == 'pop' || $1 == 'p' ]]; then
-	if [[ $# -gt 2 ]]; then
-		[[ -t 1 ]] && echo 'Invalid arguments: `gache pop <n>` does not accept any more arguments' >&2
-		exit $error_invalidArguments
-	fi
-
-	stashIndex=${2:-'0'}
-	if [[ ! $stashIndex =~ $intRegex ]]; then
-		[[ -t 1 ]] && echo 'Invalid arguments: `gache pop <n>` second argument must be a positive integer' >&2
-		exit $error_invalidArguments
-	fi
-
-	if [[ $stashIndex -ge ${#stashList[@]} ]]; then
-		[[ -t 1 ]] && echo 'Stash index out of bounds' >&2
-		exit $error_outOfBounds
-	fi
-
+if [[ $subcommand == 'pop' || $subcommand == 'p' ]]; then
 	echo "Popping: ${stashList[$stashIndex]}"
 	git stash pop "stash@{$stashIndex}"
 	exit 0
@@ -158,23 +143,7 @@ fi
 
 
 # gache apply|a [<n>]
-if [[ $1 == 'apply' || $1 == 'a' ]]; then
-	if [[ $# -gt 2 ]]; then
-		[[ -t 1 ]] && echo 'Invalid arguments: `gache apply <n>` does not accept any more arguments' >&2
-		exit $error_invalidArguments
-	fi
-
-	stashIndex=${2:-'0'}
-	if [[ ! $stashIndex =~ $intRegex ]]; then
-		[[ -t 1 ]] && echo 'Invalid arguments: `gache apply <n>` second argument must be a positive integer' >&2
-		exit $error_invalidArguments
-	fi
-
-	if [[ $stashIndex -ge ${#stashList[@]} ]]; then
-		[[ -t 1 ]] && echo 'Stash index out of bounds' >&2
-		exit $error_outOfBounds
-	fi
-
+if [[ $subcommand == 'apply' || $subcommand == 'a' ]]; then
 	echo "Applying: ${stashList[$stashIndex]}"
 	git stash apply "stash@{$stashIndex}"
 	exit 0
@@ -182,21 +151,10 @@ fi
 
 
 # gache drop|d <n>
-if [[ $1 == 'drop' || $1 == 'd' ]]; then
-	if [[ $# -gt 2 ]]; then
-		[[ -t 1 ]] && echo 'Invalid arguments: `gache drop <n>` does not accept any more arguments' >&2
+if [[ $subcommand == 'drop' || $subcommand == 'd' ]]; then
+	if [[ $autozeroed == 'true' ]]; then
+		[[ -t 1 ]] && echo 'Invalid arguments: `gache drop <n>` second argument must be present' >&2
 		exit $error_invalidArguments
-	fi
-
-	stashIndex=$2
-	if [[ ! $stashIndex =~ $intRegex ]]; then
-		[[ -t 1 ]] && echo 'Invalid arguments: `gache drop <n>` second argument must be a positive integer' >&2
-		exit $error_invalidArguments
-	fi
-
-	if [[ $stashIndex -ge ${#stashList[@]} ]]; then
-		[[ -t 1 ]] && echo 'Stash index out of bounds' >&2
-		exit $error_outOfBounds
 	fi
 
 	echo "Dropping: ${stashList[$stashIndex]}"
@@ -205,7 +163,7 @@ if [[ $1 == 'drop' || $1 == 'd' ]]; then
 fi
 
 
-# any other invalid arguments
+# Invalid commands
 [[ -t 1 ]] && echo 'Invalid arguments' >&2
 exit $error_invalidArguments
 
