minor comments and modifications to gache

diff --git a/scripts/gache b/scripts/gache
--- a/scripts/gache
+++ b/scripts/gache
@@ -54,7 +54,7 @@ error_outOfBounds=2
 error_stashError=3
 
 
-# gache help|h
+# gache help|h - helpdoc
 if [[ $1 =~ ^(help|h|-h|--help)$ ]]; then
 	if [[ -t 0 ]]; then
 		echo "$helpDoc" | less
@@ -65,7 +65,7 @@ if [[ $1 =~ ^(help|h|-h|--help)$ ]]; then
 fi
 
 
-# gache
+# gache - list all stashes
 if [[ $# -eq 0 ]]; then
 	stashList=$(git --no-pager stash list)
 	if [[ ${#stashList} -gt 0 ]]; then
@@ -94,15 +94,20 @@ if [[ $1 == 'save' || $1 == 's' ]]; then
 fi
 
 
-# TODO # gache index|i
-# TODO # gache <n>
+# TODO # gache index|i - stash only the indexed changes
+# TODO # gache <n> - print details about a stash
 
 
-# Commands after here work with the stash index
+# Rest of command work with format: gache <subcomand> <index>
 subcommand=$1
-shift
+stashIndex=$2
 
-stashIndex=$1
+if [[ $# -gt 2 ]]; then
+	[[ -t 1 ]] && echo 'Invalid arguments: `gache <subcommand> <n>` does not accept any more arguments' >&2
+	exit $error_invalidArguments
+fi
+
+# Autozeroed is saved for subcommands where stashIndex is mandatory
 autozeroed='false'
 if [[ -z $stashIndex ]]; then
 	stashIndex=0
@@ -127,11 +132,6 @@ if [[ $stashIndex -ge ${#stashList[@]} ]]; then
 	exit $error_outOfBounds
 fi
 
-if [[ $# -gt 1 ]]; then
-	[[ -t 1 ]] && echo 'Invalid arguments: `gache <subcommand> <n>` does not accept any more arguments' >&2
-	exit $error_invalidArguments
-fi
-
 
 # gache pop|p [<n>]
 if [[ $subcommand == 'pop' || $subcommand == 'p' ]]; then
@@ -152,7 +152,7 @@ fi
 # gache drop|d <n>
 if [[ $subcommand == 'drop' || $subcommand == 'd' ]]; then
 	if [[ $autozeroed == 'true' ]]; then
-		[[ -t 1 ]] && echo 'Invalid arguments: `gache drop <n>` second argument must be present' >&2
+		[[ -t 1 ]] && echo 'Invalid arguments: `gache drop <n>` second argument is mandatory' >&2
 		exit $error_invalidArguments
 	fi
 
@@ -162,8 +162,8 @@ if [[ $subcommand == 'drop' || $subcommand == 'd' ]]; then
 fi
 
 
-# Invalid commands
-[[ -t 1 ]] && echo 'Invalid arguments' >&2
+# Invalid subcommands
+[[ -t 1 ]] && echo 'Invalid arguments: `gache <subcommand>` invalid subcommand' >&2
 exit $error_invalidArguments
 
 
